### PR TITLE
Initial version of the fix for https://github.com/glennrp/libpng/issues/350

### PR DESCRIPTION
**Pull request by thealberto**
Hello @ioquatix ,
this is an initial version of a fix for Initial version of the fix for https://github.com/glennrp/libpng/issues/350. I'm happy to discuss it further and to improve it as needed.

Thanks

### CODE REVIEW

**Comment by ioquatix** [comment]
This looks good to me. While I don't have much opinion, do you mind following the same indentation style as the surrounding code? i.e. spaces for indentation?

**Comment by ioquatix** [comment]
One more thing, and you'll have a much better idea than me, are there other cases where we need to be concerned about this kind of issue?

**Comment by thealberto** [comment]
> This looks good to me. While I don't have much opinion, do you mind following the same indentation style as the surrounding code? i.e. spaces for indentation?

Hi,
I have updated the PR. I hope it is good enough now. Do you have as style guide that you would like us to follow?

**Comment by thealberto** [comment]
> One more thing, and you'll have a much better idea than me, are there other cases where we need to be concerned about this kind of issue?

Hi,
ATM no but I'm working on it. I would like to identify generic pattern that causes issues and fix them.

I think it is out-of-scope for this PR, but where would you like to discuss how to help `libpng` to stay alive and be updated? Is it repo a sort of replacement for it?

**Review by ioquatix — APPROVED** [review]

**Comment by ioquatix** [comment]
@thealberto Thanks for your PR and your comments. I decided to fork `libpng` because the original repo seems unmaintained. I have a lot of respect for the original maintainers but also have commercial demands and see a lot of useful PRs. I don't know what will come of this but I hope we can keep `libpng` alive and provide a place for people to contribute. I've send a message to the original maintainer to see how we can collaborate too. Hoping for a bright future and welcome your help and contributions. If you want to be added to the libpng team, let me know. However if you start by submitting PRs that's also really great.

**Comment by thealberto** [comment]
Hi @ioquatix and sorry for the delay, I'd like to participate and help `libpng` to become to stay alive. I'm happy to be part of the them but I'd like to understand the implications of it as well.

I'll continue to submit additional PR and start discussions so I can share my idea with all of you and decide together how to proceed.

Thanks a lot

**Pull request merged**
